---
networks:
  centos-a:
    ip: 127.0.0.1
    port: 10022
  centos-b:
    ip: 127.0.0.1
    port: 10023

ansible_host: "{{ networks[ inventory_hostname ].ip }}"
ansible_port: "{{ networks[ inventory_hostname ].port }}"
ansible_user: developer
ansible_ssh_private_key_file: "./centos/id_ed25519"
