version: '3'
services:
  ftpd:
    image: stilliard/pure-ftpd
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=test
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/ftpusers/test
    ports:
      - 21:21
      - 30000-30009:30000-30009
    volumes:
      - ./test:/home/ftpusers/test
