version: '3'
services:
  documentserver:
    image: onlyoffice/documentserver:latest
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secret
    volumes:
      - ./log:/var/log/onlyoffice
      #- ./data:/var/www/onlyoffice/Data
      #- ./fonts:/var/www/onlyoffice/documentserver/core-fonts:ro
    restart: always
