---
- name: debug
  hosts: all
  vars_files:
    - ../vars_files/variables.yml
  become: yes
  tasks:
  - name: check ansible_host
    ansible.builtin.debug:
      var: ansible_host

  - name: check inventory_hostname
    ansible.builtin.debug:
      var: inventory_hostname

  - name: check variables
    ansible.builtin.debug:
      msg: "{{ docker_hosts[ inventory_hostname ].ip }}"

  - name: check ansible_port
    ansible.builtin.debug:
      var: ansible_port

  - name: check local python
    ansible.builtin.debug:
      var: ansible_playbook_python

  - name: check remote python
    ansible.builtin.debug:
      var: hostvars[ inventory_hostname ].ansible_facts.python_version

  - name: change python interpreter
    set_fact: ansible_python_interpreter={{ hostvars[ inventory_hostname ].ansible_facts.env.HOME }}/.pyenv/shims/python

  - name: get python version
    shell:
      cmd: python -V
    register: python_version

  - name: show python version
    ansible.builtin.debug:
      var: python_version
