---
- name: Install epel repo
  become: yes
  hosts: all
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: installed

    - name: Disable epel repo by default
      replace:
        dest: /etc/yum.repos.d/epel.repo
        regexp: "enabled=1"
        replace: "enabled=0"
