---
- name: Postgres
  become: yes
  hosts: centos-a
  tasks:
    - name: repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

  roles:
    - postgres
