---
- name: Install pyenv
  become: yes
  hosts: all
  roles:
    # Installation required
    # $ ansible-galaxy install suzuki-shunsuke.pyenv-module
    - suzuki-shunsuke.pyenv-module
  tasks:
    - name: Install git & requirements to build python
      yum:
        name:
          - git
          - gcc
          - make
          - openssl-devel
          - libffi-devel
          - bzip2-devel
          - readline-devel
          - sqlite-devel
        state: present

    - name: Checkout pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv

    - name: pyenv install
      pyenv:
        version: miniconda3-latest
        pyenv_root: ~/.pyenv

    - name: pyenv global
      pyenv:
        subcommand: global
        versions: miniconda3-latest
        pyenv_root: ~/.pyenv
