#!/bin/bash
set -eu

# local functions
function _exists() {
  type $1 &>/dev/null
}

function _require() {
  local cmd
  local result=0
  for cmd in $*; do
    if ! _exists $cmd; then
      echo "E: not found $cmd!" >&2
      result=1
    fi
  done
  return $result
}

function install_nvim() {
  # from source

  _exists nvim && return 0

  # for Ubuntu/Debian
  echo "if false, see:"
  echo "  https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites"
  _require ninja gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

  _require git

  local install_dir=/opt/neovim
  if [ ! -d $install_dir ]; then
    sudo git https://github.com/neovim/neovim.git $install_dir
  fi

  function _make_install() {
    sudo git checkout stable
    sudo make CMAKE_BUILD_TYPE=Release
    sudo make install
  }
  (cd $install_dir && _make_install)
}
