version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "127:0.0.1:7900:7900"

  # edge:
  #   image: selenium/node-edge:4.0.0-beta-4-20210608
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "127:0.0.1:7901:7900"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-4-20210608
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "127:0.0.1:7902:7900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-20210608
    container_name: selenium-hub
    ports:
      # - "127.0.0.1:4442:4442"
      # - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
