# Generated by Django 3.2 on 2021-05-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tasks',
            field=models.ManyToManyField(to='todo.Task'),
        ),
    ]
