# Generated by Django 3.1.7 on 2021-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210509_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=32, verbose_name='タスク名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, help_text='補足説明'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=32, verbose_name='リスト名'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='tasks',
            field=models.ManyToManyField(help_text='タスク一覧', to='todo.Task'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='最終更新日'),
        ),
    ]
