version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./app:/opt/app

  app:
    build: ./gunicorn
    working_dir: /opt/app
    #command: gunicorn test_app.wsgi --bind=0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/opt/app
