version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./app:/opt/app

  app:
    build: ./gunicorn
    working_dir: /opt/app
    command: ./entorypoint.sh
    volumes:
      - ./app:/opt/app
