version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    network_mode: host
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped

volumes:
  prometheus-data:
