version: '3'
services:
  centos-a:
    build: ./centos
    ports:
      - "127.0.0.1:10022:22"
    privileged: true

   centos-b:
     build: ./centos
     ports:
       - "127.0.0.1:10023:22"
     privileged: true

  ubuntu-a:
    build: ./ubuntu
    ports:
      - "127.0.0.1:10024:22"
    privileged: true
    tty: true

